// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("om7scan")
	ScopeName = "github.com/insoft-icnp/OM7-Collector/extension/om7scanextension"
)

const (
	ExtensionStability = component.StabilityLevelDevelopment
)
